import pyarrow as pa
from google.cloud import bigquery

pq_schema = pa.schema([
    ("coin_id", pa.string()),
    ("market_cap_rank", pa.int64()),
    ("current_price_usd", pa.decimal256(76, 38)),
    ("market_cap_usd", pa.decimal256(38, 9)),
    ("fully_diluted_valuation_usd", pa.decimal256(38, 9)),
    ("total_volume_usd", pa.decimal256(38, 9)),
    ("high_24h_usd", pa.decimal256(38, 9)),
    ("low_24h_usd", pa.decimal256(38, 9)),
    ("price_change_24h_usd", pa.decimal256(38, 9)),
    ("price_change_24h_pct", pa.decimal256(38, 9)),
    ("market_cap_change_24h_usd", pa.decimal256(38, 9)),
    ("market_cap_change_24h_pct", pa.decimal256(38, 9)),
    ("circulating_supply", pa.decimal256(76, 38)),
    ("total_supply", pa.decimal256(76, 38)),
    ("max_supply", pa.decimal256(76, 38)),
    ("all_time_high_usd", pa.decimal256(76, 38)),
    ("all_time_high_change_pct", pa.decimal256(38, 9)),
    ("all_time_high_date", pa.timestamp("us", tz="UTC")),
    ("all_time_low_usd", pa.decimal256(76, 38)),
    ("all_time_low_change_pct", pa.decimal256(38, 9)),
    ("all_time_low_date", pa.timestamp("us", tz="UTC")),
    ("return_on_investment_times", pa.decimal256(76, 38)),
    ("return_on_investment_currency", pa.string()),
    ("return_on_investment_pct", pa.decimal256(38, 9)),
    ("last_updated_at", pa.timestamp("us", tz="UTC")),
    ("ingested_at", pa.timestamp("us", tz="UTC")),
    ("reference_dt", pa.date32()),
])

bq_schema = [
    bigquery.SchemaField("coin_id", "STRING"),
    bigquery.SchemaField("market_cap_rank", "INT64"),
    bigquery.SchemaField("current_price_usd", "BIGNUMERIC"),
    bigquery.SchemaField("market_cap_usd", "NUMERIC"),
    bigquery.SchemaField("fully_diluted_valuation_usd", "NUMERIC"),
    bigquery.SchemaField("total_volume_usd", "NUMERIC"),
    bigquery.SchemaField("high_24h_usd", "NUMERIC"),
    bigquery.SchemaField("low_24h_usd", "NUMERIC"),
    bigquery.SchemaField("price_change_24h_usd", "NUMERIC"),
    bigquery.SchemaField("price_change_24h_pct", "NUMERIC"),
    bigquery.SchemaField("market_cap_change_24h_usd", "NUMERIC"),
    bigquery.SchemaField("market_cap_change_24h_pct", "NUMERIC"),
    bigquery.SchemaField("circulating_supply", "BIGNUMERIC"),
    bigquery.SchemaField("total_supply", "BIGNUMERIC"),
    bigquery.SchemaField("max_supply", "BIGNUMERIC"),
    bigquery.SchemaField("all_time_high_usd", "BIGNUMERIC"),
    bigquery.SchemaField("all_time_high_change_pct", "NUMERIC"),
    bigquery.SchemaField("all_time_high_date", "TIMESTAMP"),
    bigquery.SchemaField("all_time_low_usd", "BIGNUMERIC"),
    bigquery.SchemaField("all_time_low_change_pct", "NUMERIC"),
    bigquery.SchemaField("all_time_low_date", "TIMESTAMP"),
    bigquery.SchemaField("return_on_investment_times", "BIGNUMERIC"),
    bigquery.SchemaField("return_on_investment_currency", "STRING"),
    bigquery.SchemaField("return_on_investment_pct", "NUMERIC"),
    bigquery.SchemaField("last_updated_at", "TIMESTAMP"),
    bigquery.SchemaField("ingested_at", "TIMESTAMP"),
    bigquery.SchemaField("reference_dt", "DATE"),
]